"""Enhance ReportCard model with detailed scores and feedback

Revision ID: 980c76f9e312
Revises: d1070692c2fd
Create Date: 2025-01-25 13:17:27.913325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980c76f9e312'
down_revision = 'd1070692c2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
