"""Add ReportCard model

Revision ID: b1545ba33189
Revises: 6d5a4fd6fca3
Create Date: 2025-01-25 12:03:38.729741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1545ba33189'
down_revision = '6d5a4fd6fca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
