"""Enhance ReportCard model with detailed scores and feedback

Revision ID: d1070692c2fd
Revises: b1545ba33189
Create Date: 2025-01-25 12:44:59.005051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1070692c2fd'
down_revision = 'b1545ba33189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engagement_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humor_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('empathy_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engagement_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('humor_feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('empathy_feedback', sa.Text(), nullable=True))
        batch_op.drop_column('feedback')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), nullable=True))
        batch_op.drop_column('empathy_feedback')
        batch_op.drop_column('humor_feedback')
        batch_op.drop_column('engagement_feedback')
        batch_op.drop_column('total_score')
        batch_op.drop_column('empathy_score')
        batch_op.drop_column('humor_score')
        batch_op.drop_column('engagement_score')

    # ### end Alembic commands ###
